name: face-align
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - dlib=19.24.0
  - numpy=1.26.4
  - opencv=4.10.0
  - pillow=11.1.0
  - scipy=1.15.2
  - pip:
    - mediapipe==0.10.21